# Generated by Django 6.0.1 on 2026-01-26 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities', null=True)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', help_text='Type of employment', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('INTERMEDIATE', 'Intermediate'), ('SENIOR', 'Senior'), ('EXECUTIVE', 'Executive')], default='ENTRY', help_text='Required experience level', max_length=20)),
                ('location', models.CharField(help_text='Job location', max_length=255)),
                ('is_remote', models.BooleanField(default=False, help_text='Whether the job is remote')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency code (e.g., USD, EUR)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job posting is active')),
                ('deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Job category', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.category')),
                ('employer', models.ForeignKey(help_text='Employer who posted the job', limit_choices_to={'role': 'EMPLOYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text='Cover letter from the applicant')),
                ('resume_url', models.URLField(blank=True, help_text='URL to applicant resume', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', help_text='Application status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from employer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(help_text='Job seeker applying for the job', limit_choices_to={'role': 'JOB_SEEKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', '-created_at'], name='jobs_job_categor_7d742a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer', '-created_at'], name='jobs_job_employe_3635f7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', '-created_at'], name='jobs_job_is_acti_5b4a60_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-created_at'], name='jobs_applic_job_id_6e89c3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-created_at'], name='jobs_applic_applica_a398e7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='jobs_applic_status_3928b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
